# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm build
      - run: npm test

  rsync-deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.30
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        config: ${{ secrets.SSH_CONFIG }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: rsync -azvn --exclude={'node_modules','src', 'public','.gitignore', 'README.md'} . ${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_TARGET }}/gocompass
      
